version: "3.9"
services:
  datathon_workwithdata:
    tty: true
    build: .
    ports:
      - "4000:4000"
      - "8888:8888" #Notebook port
      - "6006:6006" # Tensorboard

    container_name: "datathon_workwithdata"
    volumes:
      - ./:/appli

    networks:
      - datathon_workwithdata_network
    #  environment:
    #    HOST: ${HOST}
    #    ROOT_PWD: ${ROOT_PWD}
    #    DB: ${DB}
    #    USER: ${USERDB}
    #    USER_PWD: ${USER_PWD}

    # deploy:
    #    resources:
    #       reservations:
    #          devices:
    #             - capabilities: [gpu]
    #               driver: nvidia

networks:
  datathon_workwithdata_network:
