version: "3.9"
services:
  datathon_workwithdata:
    tty: true
    build:
      context: .
      shm_size: 256mb
    ports:
      - "4000:4000"
      - "8888:8888" #Notebook port
      - "6006:6006" # Tensorboard

    container_name: "datathon_workwithdata"
    volumes:
      - ./:/appli

    networks:
      - datathon_workwithdata_network
    environment:
      login: ${LOGIN}
      password: ${PASSWORD}

    shm_size: 512mb
    # deploy:
    #    resources:
    #       reservations:
    #          devices:
    #             - capabilities: [gpu]
    #               driver: nvidia

networks:
  datathon_workwithdata_network:
